# help

[[cmd]]
name = "Running 'dog --help' shows help"
shell = "dog --help"
stdout = { string = "dog" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running 'dog --help' shows examples"
shell = "dog --help"
stdout = { string = "Examples:" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running 'dog --help' shows query options"
shell = "dog --help"
stdout = { string = "Query options:" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running 'dog' with no arguments shows error"
shell = "dog"
stdout = { empty = true }
stderr = { string = "No domains" }
status = 3
tags = [ 'options' ]

# versions

[[cmd]]
name = "Running 'dog --version' shows version information"
shell = "dog --version"
stdout = { string = "dog" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]
